# Generated by Django 6.0 on 2026-01-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_herosettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTACard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.TextField(help_text='Motivational quote text')),
                ('verse_reference', models.CharField(default='Galatians 3:13', help_text='Bible verse reference', max_length=50)),
                ('button1_text', models.CharField(default='Books', help_text='Text for first button', max_length=100)),
                ('button1_url', models.CharField(default='#', help_text='URL for first button', max_length=200)),
                ('button2_text', models.CharField(default='School of Ministry', help_text='Text for second button', max_length=100)),
                ('button2_url', models.CharField(default='/childrens-bread-school/', help_text='URL for second button', max_length=200)),
                ('button3_text', models.CharField(default='Partner With Us', help_text='Text for third button', max_length=100)),
                ('button3_url', models.CharField(default='/donate/', help_text='URL for third button', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CTA Card',
                'verbose_name_plural': 'CTA Card',
            },
        ),
        migrations.CreateModel(
            name='InfoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('childrens_bread', "Children's Bread"), ('news', 'News'), ('word_of_truth', 'Word of Truth')], help_text='Type of card - only one card per type is displayed', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Card title (e.g., "Children\'s Bread")', max_length=200)),
                ('image', models.ImageField(help_text='Image displayed on the card', upload_to='info_cards/')),
                ('headline', models.CharField(help_text='Bold headline text below the image', max_length=200)),
                ('summary', models.TextField(help_text='Summary/description text')),
                ('author_name', models.CharField(default='TechNurtures', help_text='Author name displayed in metadata', max_length=100)),
                ('link_url', models.CharField(blank=True, help_text='URL for "Read More" link (leave blank to use default)', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Show this card on the homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Info Card',
                'verbose_name_plural': 'Info Cards',
                'ordering': ['card_type'],
            },
        ),
    ]
