# Generated by Django 6.0 on 2026-01-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_ctacard_infocard'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional video URL (e.g. YouTube embed link)'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional image shown when no video is provided', null=True, upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.TextField(help_text='Testimonial content'),
        ),
    ]
