# Generated by Django 6.0 on 2026-01-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_testimonial_video_url_alter_testimonial_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='duration_label',
            field=models.CharField(blank=True, help_text='Optional duration label shown in gallery list (e.g. "0:16")', max_length=10),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional video URL (e.g. YouTube embed link for video items)'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(help_text='Image or thumbnail for this item', upload_to='gallery/'),
        ),
    ]
