# Generated by Django 6.0 on 2026-01-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_galleryimage_duration_label_galleryimage_video_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensMinistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="Men's Ministry", max_length=200)),
                ('video_url', models.URLField(help_text="YouTube embed URL for the Men's Ministry video (e.g. https://www.youtube.com/embed/VIDEO_ID)")),
                ('description', models.TextField(help_text='Text shown next to the video')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Men's Ministry",
                'verbose_name_plural': "Men's Ministry",
                'ordering': ['-created_at'],
            },
        ),
    ]
