# Generated by Django 6.0 on 2026-01-27 13:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0008_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('start_datetime', models.DateTimeField(help_text='When the event starts')),
                ('end_datetime', models.DateTimeField(blank=True, help_text='Optional end time; leave blank for single time-slot events', null=True)),
                ('location', models.CharField(blank=True, help_text="Optional location (e.g. 'Main Auditorium' or online link)", max_length=255)),
                ('is_all_day', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Calendar Event',
                'verbose_name_plural': 'Calendar Events',
                'ordering': ['start_datetime'],
            },
        ),
    ]
