# Generated by Django 6.0 on 2026-01-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0009_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
