# Generated by Django 6.0 on 2026-01-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0010_calendarevent_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email for inquiries', max_length=254),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='event_image',
            field=models.ImageField(blank=True, help_text='Featured image for the event', null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('Service', 'Service'), ('Prayer Meeting', 'Prayer Meeting'), ('Outreach', 'Outreach'), ('Conference', 'Conference'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='external_link',
            field=models.URLField(blank=True, help_text='URL for more info or registration'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='organizer',
            field=models.CharField(blank=True, help_text='Name of the department or person in charge', max_length=100),
        ),
    ]
