# Generated by Django 6.0 on 2026-01-27 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0011_calendarevent_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ['event_date', 'title'], 'verbose_name': 'Calendar Event', 'verbose_name_plural': 'Calendar Events'},
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='event_image',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='external_link',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='is_all_day',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='color',
            field=models.CharField(default='#990030', help_text='Color code for the event label (hex format, e.g. #990030)', max_length=7),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of the event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('Service', 'Service'), ('Prayer Meeting', 'Prayer Meeting'), ('Outreach', 'Outreach'), ('Conference', 'Conference'), ('Other', 'Other')], default='Other', help_text='Type of event', max_length=50),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='location',
            field=models.CharField(blank=True, help_text='Optional location', max_length=255),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='title',
            field=models.CharField(help_text='Event or task title', max_length=200),
        ),
    ]
