# Generated by Django 6.0 on 2026-01-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0012_alter_calendarevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the event (will be displayed in event details)', null=True, upload_to='calendar_events/'),
        ),
    ]
