# Generated by Django 6.0 on 2026-01-27 19:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0013_calendarevent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocard',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Full article content triggered by "Read More"'),
        ),
        migrations.AddField(
            model_name='infocard',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='infocard',
            name='summary',
            field=models.TextField(help_text='Summary/description text (displayed on the homepage card)'),
        ),
    ]
