# Generated by Django 6.0 on 2026-01-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0014_infocard_content_infocard_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The question text', max_length=500)),
                ('answer', models.TextField(help_text='The answer text (supports HTML)')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True, help_text='Show this FAQ in the sidebar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['display_order', 'question'],
            },
        ),
    ]
