# Generated by Django 6.0 on 2026-01-27 23:39

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0015_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='image_cropping',
            field=image_cropping.fields.ImageRatioField('image', '800x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop the image to your desired size', hide_image_field=False, size_warning=True, verbose_name='image cropping'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image_cropping',
            field=image_cropping.fields.ImageRatioField('image', '800x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop the image to your desired size', hide_image_field=False, size_warning=True, verbose_name='image cropping'),
        ),
        migrations.AddField(
            model_name='herosettings',
            name='image_cropping',
            field=image_cropping.fields.ImageRatioField('image', '1920x1080', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop the hero image to your desired size', hide_image_field=False, size_warning=True, verbose_name='image cropping'),
        ),
        migrations.AddField(
            model_name='infocard',
            name='image_cropping',
            field=image_cropping.fields.ImageRatioField('image', '1600x900', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop the image to 16:9 aspect ratio (1600x900) for proper display', hide_image_field=False, size_warning=True, verbose_name='image cropping'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='image_cropping',
            field=image_cropping.fields.ImageRatioField('image', '800x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop the image to your desired size', hide_image_field=False, size_warning=True, verbose_name='image cropping'),
        ),
        migrations.AddField(
            model_name='partner',
            name='logo_cropping',
            field=image_cropping.fields.ImageRatioField('logo', '300x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop the logo to your desired size', hide_image_field=False, size_warning=True, verbose_name='logo cropping'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='photo_cropping',
            field=image_cropping.fields.ImageRatioField('photo', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop the photo to your desired size', hide_image_field=False, size_warning=True, verbose_name='photo cropping'),
        ),
    ]
