# Generated by Django 6.0 on 2026-01-28 00:13

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0016_calendarevent_image_cropping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image or thumbnail (used as fallback when no video)', upload_to='sidebar_promos/')),
                ('image_cropping', image_cropping.fields.ImageRatioField('image', '400x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop the image to your desired size (4:3 works well in sidebar)', hide_image_field=False, size_warning=True, verbose_name='image cropping')),
                ('video_url', models.URLField(blank=True, help_text='Optional video URL (e.g. YouTube embed). If set, video is shown instead of image.')),
                ('caption', models.CharField(blank=True, help_text='Optional caption below the media', max_length=200)),
                ('link_url', models.URLField(blank=True, help_text='Optional link when image/video is clicked')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sidebar Promo',
                'verbose_name_plural': 'Sidebar Promos',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
