# Generated by Django 6.0 on 2026-01-28 00:24

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0017_sidebar_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarpromo',
            name='image_cropping',
            field=image_cropping.fields.ImageRatioField('image', '300x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop to portrait 3:4. Images display as portrait in the sidebar.', hide_image_field=False, size_warning=True, verbose_name='image cropping'),
        ),
    ]
