# Generated by Django 6.0 on 2026-01-28 05:33

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0018_sidebar_promo_portrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo_cropping',
            field=image_cropping.fields.ImageRatioField('logo', '300x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Optional: Crop the logo to your desired size. Leave blank to use the original image as-is.', hide_image_field=False, size_warning=True, verbose_name='logo cropping'),
        ),
    ]
