# Generated by Django 6.0 on 2026-01-28 05:53

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0019_make_partner_logo_cropping_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='use_cropping',
            field=models.BooleanField(default=False, help_text='Check this box to enable cropping. When unchecked, the original image will be used as-is.'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo_cropping',
            field=image_cropping.fields.ImageRatioField('logo', '300x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop the logo to your desired size (only used if "Use Cropping" is checked)', hide_image_field=False, size_warning=True, verbose_name='logo cropping'),
        ),
    ]
