# Generated by Django 6.0 on 2026-01-29 05:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0020_add_use_cropping_to_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordOfTruth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.TextField(help_text='Short summary for the listing page')),
                ('content', ckeditor.fields.RichTextField(help_text='Full article content for the PDF')),
                ('is_published', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Word of Truth Article',
                'verbose_name_plural': 'Word of Truth Articles',
                'ordering': ['-published_date'],
            },
        ),
    ]
