# Generated by Django 6.0 on 2026-01-29 05:22

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0021_wordoftruth'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordoftruth',
            name='image',
            field=models.ImageField(blank=True, help_text='Featured image for the article', null=True, upload_to='word_of_truth/'),
        ),
        migrations.AddField(
            model_name='wordoftruth',
            name='image_cropping',
            field=image_cropping.fields.ImageRatioField('image', '1200x630', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop the image for the article header (recommended 1200x630)', hide_image_field=False, size_warning=True, verbose_name='image cropping'),
        ),
    ]
