# Generated by Django 6.0 on 2026-01-29 05:44

import ckeditor.fields
import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0022_wordoftruth_image_wordoftruth_image_cropping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordoftruth',
            options={'ordering': ['-created_at'], 'verbose_name': 'Word of Truth Article', 'verbose_name_plural': 'Word of Truth Articles'},
        ),
        migrations.RenameField(
            model_name='wordoftruth',
            old_name='published_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='wordoftruth',
            name='content',
        ),
        migrations.AddField(
            model_name='wordoftruth',
            name='body',
            field=ckeditor.fields.RichTextField(default='', help_text='Full article content for the PDF and web view'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wordoftruth',
            name='image_cropping',
            field=image_cropping.fields.ImageRatioField('image', '800x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop the image for proper display (800x600)', hide_image_field=False, size_warning=True, verbose_name='image cropping'),
        ),
    ]
