# Generated by Django 6.0 on 2026-01-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0023_alter_wordoftruth_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordoftruth',
            name='author_name',
            field=models.CharField(default='Breaking Barriers International', help_text='Name of the article writer', max_length=100),
        ),
    ]
