# Generated by Django 6.0 on 2026-01-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0027_aboutpage_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctacard',
            name='button2_url',
            field=models.CharField(default='/school-of-ministry/', help_text='URL for second button', max_length=200),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['is_active', 'display_order'], name='church_faq_is_acti_383d5c_idx'),
        ),
        migrations.AddIndex(
            model_name='infocard',
            index=models.Index(fields=['card_type', 'is_active'], name='church_info_card_ty_9e82bf_idx'),
        ),
        migrations.AddIndex(
            model_name='infocard',
            index=models.Index(fields=['slug'], name='church_info_slug_0ed51b_idx'),
        ),
        migrations.AddIndex(
            model_name='newsitem',
            index=models.Index(fields=['is_published', '-created_at'], name='church_news_is_publ_f002c3_idx'),
        ),
        migrations.AddIndex(
            model_name='newsitem',
            index=models.Index(fields=['slug'], name='church_news_slug_435f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['is_active', 'display_order'], name='church_part_is_acti_6f5876_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['approved', '-created_at'], name='church_test_approve_8979c9_idx'),
        ),
        migrations.AddIndex(
            model_name='verse',
            index=models.Index(fields=['is_active', 'is_featured', '-date_posted'], name='church_vers_is_acti_f2f436_idx'),
        ),
        migrations.AddIndex(
            model_name='wordoftruth',
            index=models.Index(fields=['is_published', '-created_at'], name='church_word_is_publ_682c08_idx'),
        ),
        migrations.AddIndex(
            model_name='wordoftruth',
            index=models.Index(fields=['slug'], name='church_word_slug_5097c6_idx'),
        ),
    ]
