# Generated by Django 6.0 on 2026-01-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0028_add_performance_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['event_date', 'is_published'], name='church_cale_event_d_417643_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['event_type'], name='church_cale_event_t_b65527_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['category', '-uploaded_at'], name='church_gall_categor_275606_idx'),
        ),
        migrations.AddIndex(
            model_name='sidebarpromo',
            index=models.Index(fields=['is_active', 'display_order'], name='church_side_is_acti_e38c73_idx'),
        ),
    ]
