# Generated by Django 6.0 on 2026-01-30 09:08

import ckeditor.fields
import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0029_add_remaining_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrensBread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.TextField(help_text='Short summary for the listing page')),
                ('author_name', models.CharField(default='Pst. Nellie Shani', help_text='Name of the article writer', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Featured image for the article', null=True, upload_to='childrens_bread/')),
                ('image_cropping', image_cropping.fields.ImageRatioField('image', '800x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop the image for proper display (800x600)', hide_image_field=False, size_warning=True, verbose_name='image cropping')),
                ('body', ckeditor.fields.RichTextField(help_text='Full article content')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Children's Bread Article",
                'verbose_name_plural': "Children's Bread Articles",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_published', '-created_at'], name='church_chil_is_publ_1ab53e_idx'), models.Index(fields=['slug'], name='church_chil_slug_73e656_idx')],
            },
        ),
    ]
