# Generated by Django 5.2.10 on 2026-01-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0030_childrensbread'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['display_order', 'question'], 'verbose_name': 'Common Question', 'verbose_name_plural': 'Common Questions'},
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('content_type', models.CharField(blank=True, db_index=True, help_text='Model name for article views: wordoftruth, childrensbread, news', max_length=50, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, db_index=True, help_text='PK of the article for most-read stats', null=True)),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='church_page_content_7757c3_idx'), models.Index(fields=['-viewed_at'], name='church_page_viewed__afdff0_idx')],
            },
        ),
    ]
