# Generated by Django 5.2.10 on 2026-01-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0031_pageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, help_text='Visitor IP for unique visit tracking (one visit per IP per day)', null=True),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['ip_address', '-viewed_at'], name='church_page_ip_addr_a47b4f_idx'),
        ),
    ]
