# Generated by Django 6.0 on 2026-01-30 20:24

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0032_pageview_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(help_text='Poster image', upload_to='news_line/')),
                ('image_cropping', image_cropping.fields.ImageRatioField('image', '800x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop the image to your desired size', hide_image_field=False, size_warning=True, verbose_name='image cropping')),
                ('video_url', models.URLField(blank=True, help_text='Optional YouTube video URL (e.g. https://www.youtube.com/watch?v=VIDEO_ID). If provided, video will be shown.')),
                ('summary', models.TextField(help_text='Short description or summary')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Line Item',
                'verbose_name_plural': 'News Line Items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_published', '-created_at'], name='church_news_is_publ_ca52a3_idx'), models.Index(fields=['slug'], name='church_news_slug_6d4393_idx')],
            },
        ),
    ]
