# Generated by Django 6.0 on 2026-01-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0034_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional phone number', max_length=20),
        ),
    ]
