# Generated by Django 6.0 on 2026-01-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0035_contactmessage_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(help_text='Phone number', max_length=20),
        ),
    ]
