# Generated by Django 6.0 on 2026-01-31 12:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0036_alter_contactmessage_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsline',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Full article content'),
        ),
    ]
