# Generated by Django 6.0 on 2026-01-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0037_newsline_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(help_text='Phone number', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Partner Inquiry',
                'verbose_name_plural': 'Partner Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
