# Generated by Django 6.0 on 2026-01-31 15:12

import ckeditor.fields
import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0039_mantalk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('author', models.CharField(blank=True, default='Pst. Nellie Shani', help_text='Author name', max_length=100)),
                ('cover_image', models.ImageField(help_text='Book cover image', upload_to='books/')),
                ('image_cropping', image_cropping.fields.ImageRatioField('cover_image', '600x900', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop for vertical book display (600x900)', hide_image_field=False, size_warning=True, verbose_name='image cropping')),
                ('description', models.TextField(help_text='Short description/summary for the card')),
                ('review', ckeditor.fields.RichTextField(help_text='Full book review and details')),
                ('whatsapp_number', models.CharField(default='+254716703508', help_text='WhatsApp number for inquiries', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-created_at'],
            },
        ),
    ]
