# Generated by Django 5.2.10 on 2026-02-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0040_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.FileField(help_text='Image or thumbnail for this item', upload_to='gallery/'),
        ),
    ]
