# Generated by Django 5.2.10 on 2026-02-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0040_book'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_published', '-created_at'], name='church_book_is_publ_fef5b0_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['slug'], name='church_book_slug_cd6a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['is_read', '-created_at'], name='church_cont_is_read_47bfe3_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['-created_at'], name='church_cont_created_b094c9_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerinquiry',
            index=models.Index(fields=['-created_at'], name='church_part_created_81a24d_idx'),
        ),
    ]
