# Generated by Django 6.0.2 on 2026-03-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0042_setup_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='MN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Check this to enable Maintenance Mode on the homepage')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maintenance (MN)',
                'verbose_name_plural': 'Maintenance (MN)',
            },
        ),
    ]
