# Generated by Django 5.2.10 on 2026-03-28 17:02

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0044_boardmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Main About text. Supports headings, paragraphs and bullet lists.', verbose_name='Story'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Short biography/background', verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='book',
            name='review',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Full book review and details', verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='childrensbread',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Full article content', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='infocard',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Full article content triggered by "Read More"', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='mantalk',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Full article content', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='newsline',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Full article content', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='wordoftruth',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Full article content for the PDF and web view', verbose_name='Content'),
        ),
    ]
