# Generated by Django 6.0.2 on 2026-04-22 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0045_alter_aboutpage_body_alter_boardmember_bio_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('author_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Optional email for the commenter', max_length=254)),
                ('content', models.TextField()),
                ('is_approved', models.BooleanField(default=True, help_text='Checked by default. Uncheck to hide this comment.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Article Comment',
                'verbose_name_plural': 'Article Comments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'is_approved', '-created_at'], name='church_arti_content_9055d9_idx')],
            },
        ),
    ]
