# Generated by Django 6.0.2 on 2026-04-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0046_articlecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='email',
            field=models.EmailField(help_text='Mandatory email for the commenter', max_length=254),
        ),
    ]
