# Generated by Django 5.2.10 on 2026-04-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0047_alter_articlecomment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mn',
            name='estimated_end_time',
            field=models.DateTimeField(blank=True, help_text='When the maintenance is expected to end', null=True),
        ),
        migrations.AddField(
            model_name='mn',
            name='show_timer',
            field=models.BooleanField(default=True, help_text='Whether to show the countdown timer on the maintenance page'),
        ),
        migrations.AddField(
            model_name='mn',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='When this maintenance period started (used for progress bar)', null=True),
        ),
    ]
