# Generated by Django 5.2.10 on 2026-04-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0048_mn_estimated_end_time_mn_show_timer_mn_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mn',
            name='message',
            field=models.TextField(blank=True, help_text='Custom message to display on the maintenance page (defaults to standard text if blank)'),
        ),
    ]
