# Generated by Django 5.2.10 on 2026-04-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0049_mn_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='mn',
            name='duration',
            field=models.IntegerField(blank=True, choices=[(5, '5 Minutes'), (10, '10 Minutes'), (20, '20 Minutes'), (60, '1 Hour'), (1440, '1+ Day')], help_text='Select how long the maintenance will take. This will automatically calculate the end time.', null=True),
        ),
    ]
