"""
Django settings for church_app project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

import os

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    SECRET_KEY = 'django-insecure-np3^#88u=exi*1xe1^bl5__@g7#yr$&cps2o-jwx)y%cp#=1$5'

# SECURITY WARNING: don't run with debug turned on in production!
# Default to True for local development, False for production
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    'bbi-international-1073897174388.europe-north2.run.app',
    'bbi-international-1073897174388.europe-west1.run.app',
    'bb-international.org',
    'www.bb-international.org',
    'localhost',
    '127.0.0.1',
    '.a.run.app',
    '.run.app'
]
if os.environ.get('ALLOWED_HOSTS') and os.environ.get('ALLOWED_HOSTS') != '*':
   ALLOWED_HOSTS += [h.strip() for h in os.environ.get('ALLOWED_HOSTS').split(',') if h.strip()]

CSRF_TRUSTED_ORIGINS = [
    'https://bbi-international-1073897174388.europe-north2.run.app',
    'https://bbi-international-1073897174388.europe-west1.run.app',
    'https://bb-international.org',
    'https://www.bb-international.org',
]

# Ensure custom domain is always trusted for CSRF (admin login).
if os.environ.get('CUSTOM_DOMAIN'):
    custom_domain = os.environ.get('CUSTOM_DOMAIN').strip()
    if custom_domain:
        for origin in (f'https://{custom_domain}', f'https://www.{custom_domain}'):
            if origin not in CSRF_TRUSTED_ORIGINS:
                CSRF_TRUSTED_ORIGINS.append(origin)

# Force DB sessions to avoid cache/memory issues on Cloud Run
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# FIREBASE HOSTING REQUIREMENT:
# Firebase strips ALL cookies except "__session".
# We must rename our session cookie to exactly using this key.
SESSION_COOKIE_NAME = '__session'
SESSION_COOKIE_AGE = 1209600
SESSION_SAVE_EVERY_REQUEST = True

# Store CSRF token inside the session (DB) because we cannot send a separate
# 'csrftoken' cookie (Firebase will strip it).
CSRF_USE_SESSIONS = True

# Security settings (Firebase terminates SSL, but we can usually set these)
# Keeping them False for now to ensure no other blockers, but __session usually works.
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_DOMAIN = None
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Cloud Run / other service URLs that serve this app (so staff login works on run.app too)
_extra_origins = os.environ.get('CSRF_EXTRA_ORIGINS', '').strip() or os.environ.get('CLOUD_RUN_URL', '').strip()
for o in _extra_origins.split(','):
    o = o.strip()
    if o and o not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(o)
# Fallback: ensure known Cloud Run URL is trusted if not in env (e.g. DEBUG=True run)
_run_app_origin = 'https://bbi-international-1073897174388.europe-north2.run.app'
if _run_app_origin not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(_run_app_origin)

# Log CSRF failures (Referer/Origin) to debug admin login loop
CSRF_FAILURE_VIEW = 'church_app.urls.csrf_failure_view'

# Security Hardening
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# django-ipware: client IP for analytics (unique visitors). Checks X-Forwarded-For,
# X-Real-IP, CF-Connecting-IP, etc., so tracking works behind load balancers/CDNs.
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
# Optional: set IPWARE_PROXY_COUNT=1 if behind a single LB; or IPWARE_TRUSTED_PROXY_IPS
# to a list of proxy IPs for stricter anti-spoofing.
# Redirect to HTTPS in production
# Note: SECURE_SSL_REDIRECT is disabled because Cloud Run handles SSL termination
# and enabling it causes redirect loops
# Ensure cookies are associated with the custom domain if available - handled above


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'church.diagnostic_middleware': {  # Specific logger for our middleware
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

if not DEBUG:
    SECURE_SSL_REDIRECT = False  # Cloud Run handles HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    



# Application definition

INSTALLED_APPS = [
    'jazzmin',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'ckeditor_uploader',
    'image_cropping',
    'easy_thumbnails',
    'church',
]

if os.environ.get('GS_BUCKET_NAME'):
    INSTALLED_APPS += ['storages']

try:
    import debug_toolbar  # noqa: F401
    _debug_toolbar_available = False # User requested removal
except ImportError:
    _debug_toolbar_available = False

if _debug_toolbar_available:
    INSTALLED_APPS += ['debug_toolbar']

MIDDLEWARE = [
    'church.diagnostic_middleware.HeaderLoggingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    *(['debug_toolbar.middleware.DebugToolbarMiddleware'] if _debug_toolbar_available else []),
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'church.proxy_fix.ProxyRefererFixMiddleware',  # before CSRF so admin login works when proxy strips Referer
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # REQUIRED: Populates request.user
    'church.diagnostic_middleware.ProxyRefererFixMiddleware',  # Fix Referer for admin login
    # 'church.diagnostic_middleware.StaffLoginRedirectMiddleware',  # DISABLE LOOP CAUSE
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'church.middleware.PageViewMiddleware',
]

ROOT_URLCONF = 'church_app.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'church' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'church_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.environ.get('DATABASE_URL'):
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(conn_max_age=600, ssl_require=True)
    }
    if os.environ.get('REPLICA_DATABASE_URL'):
        DATABASES['replica'] = dj_database_url.config(
            env='REPLICA_DATABASE_URL',
            conn_max_age=600,
            ssl_require=True,
        )
        DATABASE_ROUTERS = ['church_app.db_router.ReplicaRouter']
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Cache - Redis when REDIS_URL is set, else in-memory (dev)
REDIS_URL = os.environ.get('REDIS_URL')
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
                'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
                'IGNORE_EXCEPTIONS': True,
            },
            'KEY_PREFIX': 'bbi',
            'TIMEOUT': 300,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'bbi-default',
            'KEY_PREFIX': 'bbi',
            'TIMEOUT': 300,
        }
    }

CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = 300
CACHE_MIDDLEWARE_KEY_PREFIX = 'bbi'


# Logging configuration for monitoring and debugging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'] + (['file'] if not DEBUG else []),
            'level': 'INFO',
        },
        'django.db.backends': {
            'handlers': ['console'] if DEBUG else [],
            'level': 'DEBUG' if DEBUG else 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'] + (['file'] if not DEBUG else []),
            'level': 'ERROR',
            'propagate': False,
        },
        'church': {
            'handlers': ['console'] + (['file'] if not DEBUG else []),
            'level': 'INFO',
        },
        'church_app': {  # Explicit logger for project-level files like urls.py
            'handlers': ['console'] + (['file'] if not DEBUG else []),
            'level': 'INFO',
        },
    },
    'root': {
        'handlers': ['console'] + (['file'] if not DEBUG else []),
        'level': 'WARNING',
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
#
# IMPORTANT: these must be absolute URLs (start with "/") in production,
# otherwise pages under subpaths (e.g. /info-card/...) will emit relative
# asset URLs (e.g. "static/...") which then 404.

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',

]





# Media files (User uploaded content)
# Using Django 4.2+ STORAGES dict format for compatibility with Django 5.2
if os.environ.get('GS_BUCKET_NAME'):
    GS_BUCKET_NAME = os.environ.get('GS_BUCKET_NAME')
    GS_DEFAULT_ACL = os.environ.get('GS_DEFAULT_ACL', None)
    GS_QUERYSTRING_AUTH = False
    GS_FILE_OVERWRITE = False
    GS_LOCATION = os.environ.get('GS_LOCATION', '')
    
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.gcloud.GoogleCloudStorage',
            'OPTIONS': {
                'bucket_name': GS_BUCKET_NAME,
                'querystring_auth': False,
            },
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }
    # Direct GCS URL for media in production - ensures thumbnails resolve correctly
    MEDIA_URL = f"https://storage.googleapis.com/{GS_BUCKET_NAME}/"
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            # Use CompressedStaticFilesStorage in DEBUG mode (no manifest required)
            # Use CompressedManifestStaticFilesStorage in production (requires manifest)
            'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage' if DEBUG else 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }
    MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'

# CKEditor Configuration
CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
    },
}

# Easy Thumbnails Configuration
# Use the same storage as default media so thumbnail URLs and files match (local /media/, prod GCS)
THUMBNAIL_DEFAULT_STORAGE = (
    'storages.backends.gcloud.GoogleCloudStorage'
    if os.environ.get('GS_BUCKET_NAME')
    else 'django.core.files.storage.FileSystemStorage'
)
THUMBNAIL_DEBUG = DEBUG
THUMBNAIL_PRESERVE_EXTENSIONS = False  # Use consistent extensions for thumbnails
THUMBNAIL_CHECK_CACHE_MISS = True  # Check if thumbnail exists before generating
THUMBNAIL_ALWAYS_GENERATE = False  # Don't generate thumbnails on every request
THUMBNAIL_QUALITY = 85  # Default quality for JPEG thumbnails
from easy_thumbnails.conf import Settings as thumbnail_settings
THUMBNAIL_PROCESSORS = (
    'image_cropping.thumbnail_processors.crop_corners',
) + thumbnail_settings.THUMBNAIL_PROCESSORS

# Custom thumbnail namer to include 'box' parameter in filenames
# This ensures thumbnails with different crop boxes are treated as separate files
THUMBNAIL_NAMER = 'church.thumbnail_namer.custom_namer'

# Image cropping widget settings
# Configure the thumbnail size used by django-image-cropping widget in admin
IMAGE_CROPPING_THUMB_SIZE = (300, 300)  # Size for admin preview thumbnails
IMAGE_CROPPING_SIZE_WARNING = True

THUMBNAIL_ALIASES = {
    '': {
        'small': {'size': (100, 100), 'crop': 'smart'},
        'medium': {'size': (400, 400), 'crop': 'smart'},
        'large': {'size': (800, 600), 'crop': 'smart'},
        'info_card': {'size': (1600, 900), 'crop': 'smart'},
    },
}

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240
FILE_UPLOAD_TEMP_DIR = None  # Use system temp directory
FILE_UPLOAD_PERMISSIONS = 0o644

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django Debug Toolbar (dev only - DEBUG=True and package installed)
if _debug_toolbar_available:
    INTERNAL_IPS = ['127.0.0.1', 'localhost', '::1']

# Jazzmin Settings
JAZZMIN_SETTINGS = {
    "site_title": "Breaking Barriers Admin",
    "site_header": "Breaking Barriers",
    "site_brand": "BBI Admin",
    "site_logo": "images/logo.png",
    "login_logo": "images/logo.png",
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": "images/logo.png",
    "welcome_sign": "Welcome to Breaking Barriers International",
    "copyright": "Breaking Barriers International",
    "search_model": ["auth.User", "church.Verse"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"], "icon": "fas fa-tachometer-alt"},
        {"name": "Analytics", "url": "/analytics/", "icon": "fas fa-chart-line"},
        {"name": "News Line", "url": "/news-line/", "icon": "fas fa-newspaper", "new_window": True},
        {
            "name": "Hero & Homepage",
            "children": [
                {"name": "Hero Cards (3 cards)", "url": "admin:church_infocard_changelist", "icon": "fas fa-th-large"},
                {"name": "Children's Bread Articles", "url": "admin:church_childrensbread_changelist", "icon": "fas fa-bread-slice"},
                {"name": "Word of Truth Articles", "url": "admin:church_wordoftruth_changelist", "icon": "fas fa-bible"},
                {"name": "ManTalk Articles", "url": "admin:church_mantalk_changelist", "icon": "fas fa-users"},
                {"name": "News Line Articles", "url": "admin:church_newsitem_changelist", "icon": "fas fa-newspaper"},
            ],
            "icon": "fas fa-home",
        },
        {
            "name": "Content",
            "children": [
                {"name": "Verses", "url": "admin:church_verse_changelist", "icon": "fas fa-bible"},
                {"name": "About Page", "url": "admin:church_aboutpage_changelist", "icon": "fas fa-info-circle"},
                {"name": "Gallery", "url": "admin:church_galleryimage_changelist", "icon": "fas fa-images"},
                {"name": "Testimonials", "url": "admin:church_testimonial_changelist", "icon": "fas fa-comment-dots"},
            ],
            "icon": "fas fa-file-alt",
        },
        {
            "name": "Calendar & Events",
            "children": [
                {"name": "Calendar Events", "url": "admin:church_calendarevent_changelist", "icon": "fas fa-calendar-alt"},
            ],
            "icon": "fas fa-calendar-check",
        },
        {
            "name": "Site & Settings",
            "children": [
                {"name": "Hero Image", "url": "admin:church_herosettings_changelist", "icon": "fas fa-image"},
                {"name": "CTA Card", "url": "admin:church_ctacard_changelist", "icon": "fas fa-bullhorn"},
                {"name": "Sidebar Promos", "url": "admin:church_sidebarpromo_changelist", "icon": "fas fa-ad"},
                {"name": "Common Questions", "url": "admin:church_faq_changelist", "icon": "fas fa-question-circle"},
                {"name": "Partners", "url": "admin:church_partner_changelist", "icon": "fas fa-handshake"},
                {"name": "Men's Ministry", "url": "admin:church_mensministry_changelist", "icon": "fas fa-users"},
            ],
            "icon": "fas fa-cog",
        },
        {"name": "Support", "url": "https://wa.me/254717157165", "new_window": True, "icon": "fab fa-whatsapp"},
        {"model": "auth.User", "icon": "fas fa-user"},
        {"app": "church", "icon": "fas fa-church"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["auth", "church"],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "church": "fas fa-church",
        "church.Verse": "fas fa-bible",
        "church.NewsItem": "fas fa-newspaper",
        "church.CalendarEvent": "fas fa-calendar-alt",
        "church.Testimonial": "fas fa-comment-dots",
        "church.GalleryImage": "fas fa-images",
        "church.HeroSettings": "fas fa-image",
        "church.AboutPage": "fas fa-info-circle",
        "church.InfoCard": "fas fa-th-large",
        "church.ChildrensBread": "fas fa-bread-slice",
        "church.WordOfTruth": "fas fa-book-open",
        "church.ManTalk": "fas fa-users",
        "church.CTACard": "fas fa-bullhorn",
        "church.MensMinistry": "fas fa-users",
        "church.Partner": "fas fa-handshake",
        "church.NewsletterSubscriber": "fas fa-envelope",
        "church.SchoolMinistryEnrollment": "fas fa-graduation-cap",
        "church.SidebarPromo": "fas fa-ad",
        "church.FAQ": "fas fa-question-circle",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": "admin/css/custom_admin.css",
    "custom_js": "admin/js/image_preview_refresh.js",
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-danger",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_fixed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-danger",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_accelerator": True,
    "sidebar_theme": "outline",
    "sidebar_nav_child_hide_on_collapse": False,
    "no_sidebar_link_border": False,
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}