apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/build-enable-automatic-updates: 'false'
    run.googleapis.com/build-id: 7ef85e1f-4a65-4fce-ba90-79dcc9ea5178
    run.googleapis.com/build-image-uri: europe-north2-docker.pkg.dev/gen-lang-client-0549116861/cloud-run-source-deploy/bbi-international
    run.googleapis.com/build-name: projects/1073897174388/locations/europe-north2/builds/7ef85e1f-4a65-4fce-ba90-79dcc9ea5178
    run.googleapis.com/build-source-location: gs://run-sources-gen-lang-client-0549116861-europe-north2/services/bbi-international/1770263213.248396-18b581237873437e9cf99be1b78a35d0.zip#1770263269333722
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/maxScale: '20'
    run.googleapis.com/urls: '["https://bbi-international-1073897174388.europe-north2.run.app","https://bbi-international-gyosnq7vca-ma.a.run.app"]'
  labels:
    cloud.googleapis.com/location: europe-north2
  name: bbi-international
  namespace: '1073897174388'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '20'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 554.0.0
        run.googleapis.com/cloudsql-instances: gen-lang-client-0549116861:europe-north2:bbinternational-db
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: rogeztdeqg
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: DATABASE_URL
          value: postgresql://neondb_owner:npg_OsJiLV86Bkdn@ep-damp-water-aht3z7in-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
        - name: GS_BUCKET_NAME
          value: bbinternational-media
        - name: GS_PROJECT_ID
          value: gen-lang-client-0549116861
        - name: DEBUG
          value: 'False'
        - name: ALLOWED_HOSTS
          value: '*'
        - name: SECRET_KEY
          value: django-insecure-prod-key
        - name: CSRF_TRUSTED_ORIGINS
          value: https://bbi-international-gyosnq7vca-ew.a.run.app,https://bbi-international-1073897174388.europe-north2.run.app,https://bb-international.org,https://www.bb-international.org,https://gen-lang-client-0549116861.web.app
        - name: CUSTOM_DOMAIN
          value: bb-international.org
        image: us-docker.pkg.dev/cloudrun/container/hello
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 1073897174388-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - percent: 100
    revisionName: bbi-international-00120-5b5
