from django.urls import path
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('offline/', TemplateView.as_view(template_name='church/offline.html'), name='offline'),
    path('about/', views.about_view, name='about'),
    path('word-of-truth/', views.word_of_truth_list_view, name='word_of_truth_list'),
    path('word-of-truth/load-more/', views.load_more_word_of_truth_view, name='load_more_word_of_truth'),
    path('word-of-truth/<slug:slug>/', views.word_of_truth_detail_view, name='word_of_truth_detail'),
    path('word-of-truth/<slug:slug>/pdf/', views.word_of_truth_pdf_view, name='word_of_truth_pdf'),
    path('childrens-bread/', views.childrens_bread_list_view, name='childrens_bread_list'),
    path('childrens-bread/load-more/', views.load_more_childrens_bread_view, name='load_more_childrens_bread'),
    path('childrens-bread/<slug:slug>/', views.childrens_bread_detail_view, name='childrens_bread_detail'),
    path('childrens-bread-school/', views.childrens_bread_school_view, name='childrens_bread_school'),
    path('school-of-ministry/', views.school_of_ministry_view, name='school_of_ministry'),
    path('media/', views.media_view, name='media'),
    path('contact-us/', views.contact_us_view, name='contact_us'),
    path('news/', views.news_list_view, name='news_list'),
    path('news/<slug:slug>/', views.news_detail_view, name='news_detail'),
    path('news/load-more/', views.load_more_news_view, name='load_more_news'),
    path('news-line/', views.news_line_list_view, name='news_line_list'),
    path('news-line/load-more/', views.load_more_news_line_view, name='load_more_news_line'),
    path('info-card/<slug:slug>/', views.info_card_detail_view, name='info_card_detail'),
    path('api/calendar-event/create/', views.calendar_event_create_view, name='calendar_event_create'),
    path('api/calendar-event/<int:event_id>/', views.calendar_event_detail_view, name='calendar_event_detail'),
    path('api/calendar-event/<int:event_id>/edit/', views.calendar_event_edit_view, name='calendar_event_edit'),
    path('api/calendar-event/<int:event_id>/delete/', views.calendar_event_delete_view, name='calendar_event_delete'),
    path('gallery/', views.gallery_view, name='gallery'),
    path('privacy/', views.privacy_view, name='privacy'),
    path('donate/', views.donate_view, name='donate'),
    path('search/', views.search_view, name='search'),
    path('search/autocomplete/', views.search_autocomplete_view, name='search_autocomplete'),
    path('newsletter/subscribe/', views.newsletter_subscribe_view, name='newsletter_subscribe'),
    path('analytics/', views.analytics_view, name='analytics'),
]
